import { Product } from '@/types/toy';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Oso de Peluche Gigante 1 Metro',
    slug: 'oso-de-peluche-gigante-1-metro',
    description: 'Peluche ultrasuave y acolchado de 100cm de altura. Fabricado con materiales hipoalerégenicos de primera calidad. Ideal para regalos y abrazos.',
    price: 79.90,
    original_price: 99.90,
    category: 'Peluches',
    age_range: 'Todas las edades',
    image_url: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: true,
    badge: 'Más Vendido'
  },
  {
    id: '2',
    name: 'Set de Bloques de Construcción 150 Piezas',
    slug: 'set-bloques-construccion-150-piezas',
    description: 'Set de bloques multicolores compatibles con las principales marcas. Fomenta la creatividad, psicomotricidad y visión espacial de los niños.',
    price: 49.50,
    original_price: 65.00,
    category: 'Didácticos',
    age_range: '3 a 6 años',
    image_url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: true,
    badge: 'Oferta'
  },
  {
    id: '3',
    name: 'Auto de Carreras a Control Remoto 4WD',
    slug: 'auto-carreras-control-remoto-4wd',
    description: 'Vchículo todo terreno con tracción 4x4, batería recargable USB y control remoto de 2.4GHz con alcance de hasta 40 metros.',
    price: 69.00,
    original_price: 85.00,
    category: 'Vehículos y Pistas',
    age_range: '6 a 12 años',
    image_url: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=800&auto=format&fit=crop&Q=80',
    in_stock: true,
    featured: true,
    badge: 'Nuevo'
  },
  {
    id: '4',
    name: 'Set de Doctor Infantil con Maletín y Luces',
    slug: 'set-doctor-infantil-maletin',
    description: 'Maletín médico con estetoscopio con sonido de latidos reales, termómetro con luz, jeringa y accesorios médicos seguros sin bordes filosos.',
    price: 38.00,
    original_price: 45.00,
    category: 'Juegos de Rol',
    age_range: '3 a 8 años',
    image_url: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: false,
    badge: 'Popular'
  },
  {
    id: '5',
    name: 'Juego de Mesa Familiar - La Torre de Madera',
    slug: 'juego-mesa-torre-madera',
    description: 'Juego clásico de equilibrio y destreza con 54 bloques de madera pulida natural. Diversión garantizada para reuniones familiares y amigos.',
    price: 28.50,
    original_price: null,
    category: 'Juegos de Mesa',
    age_range: '5+ años',
    image_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: false,
    badge: null
  },
  {
    id: '6',
    name: 'Muñeca Articulada con Vestidos y Accesorios',
    slug: 'muneca-articulada-vestidos-accesorios',
    description: 'Muñeca articulada de 30 cm con 3 cambios de ropa, zapatos, peine y accesorios para peinar. Cabello suave y ojos brillantes.',
    price: 42.00,
    original_price: 55.00,
    category: 'Muñecas',
    age_range: '3 a 9 años',
    image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&Q=80',
    in_stock: true,
    featured: true,
    badge: 'Destacado'
  },
  {
    id: '7',
    name: 'Gimnasio Musical para Bebés con Piano Téctil',
    slug: 'gimnasio-musical-bebes-piano',
    description: 'Tapete acolchado suave con arco de juguetes colgantes sonajeros y piano pateador con luces y melodáas estimulantes para bebés.',
    price: 89.00,
    original_price: 110.00,
    category: 'Bebés',
    age_range: '0 a 18 meses',
    image_url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: false,
    badge: 'Recomendado'
  },
  {
    id: '8',
    name: 'Dinosaurio T-Rex con Sonido y Rugido',
    slug: 'dinosaurio-t-rex-sonido-rugido',
    description: 'Figura de acción de Tyrannosaurus Rex de 40cm con rugido realista, ojos iluminados y mandíbula articulada con detalles de alta calidad.',
    price: 55.00,
    original_price: 68.00,
    category: 'Figuras de Acción',
    age_range: '4 a 10 años',
    image_url: 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?w=800&auto=format&fit=crop&q=80',
    in_stock: false,
    featured: false,
    badge: 'Agotado'
  }
];