import { Product } from '@/types/toy';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Oso de Peluche Gigante 1 Metro',
    slug: 'oso-de-peluche-gigante-1-metro',
    description: 'Peluche ultrasuave y acolchado de 100cm de altura. Fabricado con materiales hipoalergénicos de primera calidad. Ideal para regalos y abrazos.',
    price: 79.90,
    original_price: 99.90,
    category: 'Peluches',
    age_range: 'Todas las edades',
    gender: 'unisex',
    image_url: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: true,
    badge: 'Más Vendido'
  },
  {
    id: '2',
    name: 'Set de Bloques de Construcción 150 Piezas',
    slug: 'set-bloques-construccion-150-piezas',
    description: 'Set de bloques multicolores compatibles. Fomenta la creatividad, psicomotricidad y visión espacial de los niños.',
    price: 49.50,
    original_price: 65.00,
    category: 'Didácticos',
    age_range: '3 a 6 años',
    gender: 'unisex',
    image_url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: true,
    badge: 'Oferta'
  },
  {
    id: '3',
    name: 'Auto de Carreras a Control Remoto 4WD',
    slug: 'auto-carreras-control-remoto-4wd',
    description: 'Vehículo todo terreno con tracción 4x4, batería recargable USB y control remoto de 2.4GHz con alcance de hasta 40 metros.',
    price: 69.00,
    original_price: 85.00,
    category: 'Vehículos y Pistas',
    age_range: '6 a 12 años',
    gender: 'niños',
    image_url: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: true,
    badge: 'Nuevo'
  },
  {
    id: '4',
    name: 'Set de Cocina Infantil con Sonidos y Luces',
    slug: 'set-cocina-infantil-sonidos-luces',
    description: 'Cocina interactiva con sartenes, ollas, utensilios y vaporizador de agua simulado para horas de juego creativo.',
    price: 65.00,
    original_price: 80.00,
    category: 'Juegos de Rol',
    age_range: '3 a 8 años',
    gender: 'niñas',
    image_url: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: true,
    badge: 'Popular'
  },
  {
    id: '5',
    name: 'Juego de Mesa Familiar - La Torre de Madera',
    slug: 'juego-mesa-torre-madera',
    description: 'Juego clásico de equilibrio y destreza con 54 bloques de madera pulida natural. Diversión garantizada para reuniones familiares.',
    price: 28.50,
    original_price: null,
    category: 'Juegos de Mesa',
    age_range: '5+ años',
    gender: 'unisex',
    image_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: false,
    badge: null
  },
  {
    id: '6',
    name: 'Muñeca Articulada Princesa Mágica con Vestidos',
    slug: 'muneca-articulada-princesa-magica',
    description: 'Muñeca articulada de 30 cm con 3 cambios de ropa, zapatos, corona, peine y accesorios para peinar. Cabello suave y brillante.',
    price: 45.00,
    original_price: 58.00,
    category: 'Muñecas',
    age_range: '3 a 9 años',
    gender: 'niñas',
    image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: true,
    badge: 'Destacado'
  },
  {
    id: '7',
    name: 'Gimnasio Musical para Bebés con Piano Táctil',
    slug: 'gimnasio-musical-bebes-piano',
    description: 'Tapete acolchado suave con arco de juguetes colgantes sonajeros y piano pateador con luces y melodías estimulantes para bebés.',
    price: 89.00,
    original_price: 110.00,
    category: 'Bebés',
    age_range: '0 a 18 meses',
    gender: 'unisex',
    image_url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: false,
    badge: 'Recomendado'
  },
  {
    id: '8',
    name: 'Dinosaurio T-Rex Robótico con Rugido y Luces',
    slug: 'dinosaurio-t-rex-robotico-rugido',
    description: 'Figura articulada de Tyrannosaurus Rex de 40cm que camina, ruge y tiene ojos iluminados con detalles realistas de alta calidad.',
    price: 58.00,
    original_price: 72.00,
    category: 'Figuras de Acción',
    age_range: '4 a 10 años',
    gender: 'niños',
    image_url: 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: false,
    badge: 'Nuevo'
  },
  {
    id: '9',
    name: 'Castillo de Princesas con Luces y Mobiliario',
    slug: 'castillo-princesas-luces-mobiliario',
    description: 'Hermoso palacio de dos pisos con muebles en miniatura, efectos de luz, escalera real y figuritas incluidas.',
    price: 85.00,
    original_price: 105.00,
    category: 'Muñecas',
    age_range: '3 a 8 años',
    gender: 'niñas',
    image_url: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: true,
    badge: 'Favorito'
  },
  {
    id: '10',
    name: 'Pista de Autos Doble Loop con Lanzador',
    slug: 'pista-autos-doble-loop-lanzador',
    description: 'Pista de carreras de alta velocidad con 2 autos incluidos, acelerador manual y giro de 360 grados.',
    price: 52.00,
    original_price: 68.00,
    category: 'Vehículos y Pistas',
    age_range: '5 a 11 años',
    gender: 'niños',
    image_url: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80',
    in_stock: true,
    featured: false,
    badge: 'Oferta'
  }
];